variables:
  # Global
  demo_name: "fab-demo-tutorial-lakehouse"
<<<<<<< HEAD
  capacity_name: "Trial-20240216T095351Z-aiYznZSl4kS24GSzM6Yejw"
  workspace_name: "_ws_fab_tutorial_lakehouse_001"
=======
  capacity_name: "cosmosdbmirroring"
  workspace_name: "_ws_fab_tutorial_lakehouse_03"
>>>>>>> 09ff4b0d92c9e9e4093c7cd3534786694d893d33
  domain_name: "tutorials"
  lakehouse_name: "wwilakehouse"

  # SPN auth
  enable_spn_auth: "false"
  upn_objectid: "395d4722-e034-4fe5-a95c-525d5b0adeeb"

  # Internals - do not touch
  staging_dir: "./tmp"
