variables:
  # Global
  demo_name: "fab-demo-tutorial-lakehouse"
  capacity_name: "cosmosdbmirroring"
  workspace_name: "_ws_fab_tutorial_lakehouse_01"
  domain_name: "tutorials"
  lakehouse_name: "wwilakehouse"

  # Internals - do not touch
  staging_dir: "./tmp"
