variables:
  # Global
  demo_name: "fab-demo-tutorial-lakehouse"
<<<<<<< HEAD
  capacity_name: "Trial-20240216T095351Z-aiYznZSl4kS24GSzM6Yejw"
  workspace_name: "_ws_fab_tutorial_lakehouse_upn2"
=======
  capacity_name: "cosmosdbmirroring"
  workspace_name: "_ws_fab_tutorial_lakehouse_01"
>>>>>>> 08d9a84f389be3dcf5e74d1d09f1923f7ac65896
  domain_name: "tutorials"
  lakehouse_name: "wwilakehouse"

  # SPN auth
  enable_spn_auth: "false"
  upn_objectid: "395d4722-e034-4fe5-a95c-525d5b0adeeb"

  # Internals - do not touch
  staging_dir: "./tmp"
