variables:
  # Global
  demo_name: "fab-demo-tutorial-lakehouse"
  capacity_name: "Trial-20240216T095351Z-aiYznZSl4kS24GSzM6Yejw"
  workspace_name: "_ws_fab_tutorial_lakehouse_4"
  domain_name: "tutorials"
  lakehouse_name: "wwilakehouse"
  enable_lakehouse_schemas: "false"

  # Internals - do not touch
  staging_dir: "./tmp"
