name: fab:demo-tutorial-rti

on:
  workflow_dispatch:
    inputs:
      capacity_name:
        description: "Fabric capacity name"
        required: true
      upn_objectid:
        description: "ObjectId of the user (for SPN deployment)"
        required: true
      postfix:
        description: "Postfix for workspace name"
        required: false
        default: "01"

jobs:
  deploy-demo:
    name: Deploy RTI Tutorial
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Fabric CLI
        run: |
          python -m pip install dist/fabric_cli-0.1.6-py3-none-any.whl

      - name: Deploy tutorial
        env:
          FAB_CLIENT_ID: ${{ secrets.FAB_CLIENT_ID }}
          FAB_CLIENT_SECRET: ${{ secrets.FAB_CLIENT_SECRET }}
          FAB_TENANT_ID: ${{ secrets.FAB_TENANT_ID }}
        run: |
          fab -c "config set fab_encryption_fallback_enabled true"
          bash fab-demo-tutorial-rti/scripts/setup.sh
