name: fab:demo-tutorial-lakehouse

on:
  workflow_dispatch:

jobs:
  setup-and-run-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Fabric CLI from whl
        run: |
          python -m pip install dist/fabric_cli-0.1.5-py3-none-any.whl
      - name: Set environment variables
        env:
          FAB_TOKEN: ${{ secrets.FABRIC_TOKEN }}
          FAB_TOKEN_ONELAKE: ${{ secrets.FABRIC_TOKEN_ONELAKE }}
          FAB_TOKEN_AZURE: ${{ secrets.FABRIC_TOKEN_AZURE }}
          FAB_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
        run: |
          echo "Environment variables set."
      - name: Run Fabric CLI commands
        env:
          FAB_TOKEN: ${{ secrets.FABRIC_TOKEN }}
          FAB_TOKEN_ONELAKE: ${{ secrets.FABRIC_TOKEN_ONELAKE }}
          FAB_TOKEN_AZURE: ${{ secrets.FABRIC_TOKEN_AZURE }}
          FAB_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
        run: |
          fab -c "ls"